import type { Metadata } from "next";

import "./globals.css";

import { Providers } from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#0b0c10] text-white antialiased ${GeistSans.className}">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
